### ISSUE TITLE
Pending pull requests

### ISSUE THREAD

**Issue by vaibhavsood** [tianon/jenkins-groovy#10]
Hi Tianon,

There were some pull requests for groovy scripts which I had created on this repo which were pending review, I just wanted to know if you had any comments for them or any suggestions to make any changes

Thanks,
Vaibhav

**Comment by tianon** [comment]
Thanks for the prod -- sorry it's taken me so long to get around to reviewing those! :disappointed:

**Comment by vaibhavsood** [comment]
Sure, thanks a lot for the review comments!!
