### ISSUE TITLE
Images for maven, neo4j, solr

### ISSUE THREAD

**Issue by vaibhavsood** [tianon/jenkins-groovy#11]
Hi Tianon,

For the maven,neo4j and solr groovy scripts the corresponding docker images don't seem to have come up under docker hub

It looks like all of them use java as the base image but the docker hub java image for some multiarch platforms dont have the openjdk-*-jdk/jre tags. I'm not sure how exactly these alternate tags get created (I guess should be via openjdk.groovy but not sure). 

For eg, s390x seems to have the correct tags but ppc64le has them missing
https://hub.docker.com/r/s390x/java/tags/
https://hub.docker.com/r/ppc64le/java/tags/

Wanted to check regarding the changes needed to fix this

Thanks!
Vaibhav

**Comment by tianon** [comment]
I think 7999b45 is what was needed. :disappointed:

**Comment by tianon** [comment]
Ah, another issue we're running into is https://buildd.debian.org/status/package.php?p=openjdk-9&suite=experimental -- ie, `openjdk-9` isn't available for install on s390x, so `maven:jdk-9` fails to build.

**Comment by tianon** [comment]
I've got these all as un-stuck as they can possibly be -- I think `s390x/maven` is all that's failing now. :+1:

**Comment by vaibhavsood** [comment]
Sure, thanks a lot!
