### ISSUE TITLE
multiarch alpine on ARMv8 (aarch64)

### ISSUE THREAD

**Issue by vielmetti** [tianon/jenkins-groovy#15]
Hi, I see that this commit

https://github.com/tianon/jenkins-groovy/commit/3f1e319cc46f395c7647ddd6a051bd392f8fe58c

adds support for Alpine on ARMv8 (aarch64), but there's no corresponding 

https://hub.docker.com/r/aarch64/alpine/

build. Can you point me to where that work is being done? thanks!

**Comment by yosifkit** [comment]
Currently, `apk-static` is segfaulting in alpine 3.5 so we are unable to build the image for aarch64, since that is the only version that supports aarch64.

**Comment by vielmetti** [comment]
Thanks @yosifkit - is there an issue open for that `apk-static` segfault in 3.5 somewhere?

**Comment by tianon** [comment]
I don't think so. :disappointed:

@ncopa any pointers to where we should file an issue about this? (or hints for working around it?)

It seems that the `apk-static` binary from `edge` segfaults on `aarch64` and `armhf` but not `i386` (specifically in the `aarch64` case http://dl-cdn.alpinelinux.org/alpine/edge/main/aarch64/apk-tools-static-2.6.7-r2.apk):

``` console
./mkimage-alpine.bash: line 21: 18552 Segmentation fault      (core dumped) apk --root "$rootfs" --update-cache --keys-dir /home/tianon.gravi/jenkins-slave/workspace/docker-arm64-alpine/apk-tools-edge/etc/apk/keys add --initdb ${packages[*]//,/ }
```

**Comment by vielmetti** [comment]
Thanks @tianon - I looked through what I think is the right issues page at https://bugs.alpinelinux.org/projects/alpine/issues but didn't see any report of this.

**Comment by tianon** [comment]
I'm guessing that `apk-static` isn't used all that often. :innocent:

**Comment by vielmetti** [comment]
I think this is the commit log at http://git.alpinelinux.org/cgit/aports/log/?qt=grep&q=apk-tools which would suggest that `libressl` is a new dependency that may be the next place to look.

**Comment by vielmetti** [comment]
https://bugs.alpinelinux.org/issues/6372

**Comment by vielmetti** [comment]
Upstream has closed this bug: https://bugs.alpinelinux.org/issues/6372 and I'm able to build an aarch64 Docker image with the supplied scripts in the Docker distribution. @tianon , @yosifkit - can you check the Jenkins build to confirm that this is all working end to end?

**Comment by tianon** [comment]
Yeah, that appears to have fixed the `apk.static` issues, but I'm getting the following new error that I wonder if is an issue with the CDN specifically -- which mirror did you use?

```
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/aarch64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/edge/main: BAD signature
WARNING: Ignoring APKINDEX.066df28d.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/aarch64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/edge/community: BAD signature
WARNING: Ignoring APKINDEX.b53994b4.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
  alpine-baselayout (missing):
    required by: world[alpine-baselayout]
  alpine-keys (missing):
    required by: world[alpine-keys]
  apk-tools (missing):
    required by: world[apk-tools]
  libc-utils (missing):
    required by: world[libc-utils]
```

**Comment by vielmetti** [comment]
My full transcript looks like I'm picking up from nl.

```
emv@armv8hello:~/src/docker/contrib$ sudo ./mkimage-alpine.sh 
tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'
tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'
fetch http://nl.alpinelinux.org/alpine/edge/main/aarch64/APKINDEX.tar.gz
(1/16) Installing musl (1.1.15-r4)
(2/16) Installing busybox (1.25.1-r0)
Executing busybox-1.25.1-r0.post-install
(3/16) Installing alpine-baselayout (3.0.3-r2)
Executing alpine-baselayout-3.0.3-r2.pre-install
Executing alpine-baselayout-3.0.3-r2.post-install
(4/16) Installing openrc (0.21.7-r1)
Executing openrc-0.21.7-r1.post-install
(5/16) Installing alpine-conf (3.4.1-r5)
(6/16) Installing libressl2.4-libcrypto (2.4.3-r1)
(7/16) Installing libressl2.4-libssl (2.4.3-r1)
(8/16) Installing zlib (1.2.8-r2)
(9/16) Installing apk-tools (2.6.8-r1)
(10/16) Installing busybox-suid (1.25.1-r0)
(11/16) Installing busybox-initscripts (3.0-r6)
Executing busybox-initscripts-3.0-r6.post-install
(12/16) Installing scanelf (1.1.6-r0)
(13/16) Installing musl-utils (1.1.15-r4)
(14/16) Installing libc-utils (0.7-r1)
(15/16) Installing alpine-keys (1.2-r0)
(16/16) Installing alpine-base (3.4.0-r0)
Executing busybox-1.25.1-r0.trigger
OK: 5 MiB in 16 packages
alpine:edge with id=sha256:13e9d745c8c8f4ec1debdecf77481b897fcc6f747a3502eb6dfbcb084294dab0 created!
```

**Comment by vielmetti** [comment]
@tianon - I opened up the issue https://bugs.alpinelinux.org/issues/6389 in Alpine's `apk` for the "bad signature" issues that you and I are seeing with /community and /testing APKINDEX repos. The APKINDEX does seem to have a good signature for the /main repo.

**Comment by vielmetti** [comment]
The upstream issue https://bugs.alpinelinux.org/issues/6389 has been marked as resolved. @tianon @yosifkit I think this means that builds might start to work again. I'll report back from my own testing.

**Comment by tianon** [comment]
Looks good! https://hub.docker.com/r/aarch64/alpine/ :heart:!
