### ISSUE TITLE
Suggestion to update warning

### ISSUE THREAD

**Issue by bboreham** [tianon/jenkins-groovy#17]
The [opening text](https://github.com/tianon/jenkins-groovy/blob/9a50ff89ea97164ef6cd74fb7d2d837216f50483/dsl/docker-multiarch/docs.groovy#L78) of each description says:

> THEY ARE PROVIDED ON A BEST-EFFORT BASIS WHILE docker/docker#15866 IS STILL IN-PROGRESS

That issue has been closed for nearly a year now, so the wording should be updated.

**Comment by tianon** [comment]
@bboreham doh, that's an excellent point, we should redo all that wording :disappointed: :heart:
