### ISSUE TITLE
updated golang image for aarch64?

### ISSUE THREAD

**Issue by vielmetti** [tianon/jenkins-groovy#19]
There is an image 

https://hub.docker.com/r/aarch64/ubuntu-golang/

which provides a year-old version of Go (go1.5.2) under Ubuntu. I'd like to track this issue to get some more recent supportable Go image for aarch64, in part so that I can port Alex Ellis's FaaS code  to ARMv8. 

There is no official Go build for aarch64 yet; however there are PPAs for Ubuntu that provide a variety of recent builds. At the very minimum, Ubuntu xenial (16.04) comes with Go 1.6.3.

**Comment by vielmetti** [comment]
Alpine 3.6.0 ships with Go 1.8, which would be a good base for a Go container.

**Comment by yosifkit** [comment]
We have moved to [`arm64v8`](https://hub.docker.com/r/arm64v8/golang/) to be more specific than `aarch64`.  A little more info is [here](https://github.com/docker-library/official-images/tree/4bda345c0f7fca553bb65520af77399024ea945b#architectures-other-than-amd64).

**Comment by tianon** [comment]
Indeed! :+1:
