### ISSUE TITLE
armhf/pypy isn't up to date

### ISSUE THREAD

**Issue by oberstet** [tianon/jenkins-groovy#20]
https://hub.docker.com/r/armhf/pypy/ was last updated 7 month ago, while https://hub.docker.com/_/pypy/ was updated days ago

Any plans keeping both in sync, and making armhf "official" too?

**Comment by tianon** [comment]
The issue with `armhf/pypy` not staying up to date is that my `armhf` build box has limited space, so it ends up getting "stuck".  I'll go clear it out again and make sure `pypy` is rebuilt.

As for making them official, the short answer is that yes, we're trying to bring multiarchitecture back into the official images properly.  The longer answer is that there are a lot of complex moving parts we have to coordinate to make that happen, so it won't happen overnight, but it is in progress!

See https://github.com/docker-library/official-images/issues/2289 for some of that. :+1:

**Comment by oberstet** [comment]
Thanks for explaining! Looking forward .. hoping for arm64 also long run .. it's becoming a thing too (PyPy itself isn't ready, but in general).

**Comment by tianon** [comment]
Yeah, gotta convince upstream :smile: (https://bitbucket.org/pypy/pypy/downloads/)

**Comment by oberstet** [comment]
@tianon yeah, advocating for arm64, from IRC (and I will mention "pypy/arm64 needs funding" every conversations talking to guys with $$ where there is a chance):

```
<cfbolz> oberstet: out of curiosity, is arm64 going to be relevant for you at some point?
..snip
<oberstet> arm64, yes, I expect that to become a thing in the not too distant future. for now, it is more about armhf in general, and armhf/docker where there seems interest from industrial uesrs ..
<oberstet> cavium thunderx just became avail in germany now .. we are looking at getting a box
<oberstet> https://www.deltacomputer.com/hochleistungs-rechner/standard-server/arm-thunderx.html
<cfbolz> Nice. So at some point we will need a backends for that then 
<oberstet> this would rock!
```

**Comment by vielmetti** [comment]
Thanks @oberstet for speaking up for arm64. Packet has a "Type 2A" Cavium ThunderX server which has 96 ARMv8 cores, which makes for a nice build environment, and there's a Terraform provider for it which means you can go from scratch to running and configured machine in about 10 minutes.

**Comment by oberstet** [comment]
@vielmetti Thanks for the pointer to Packet! I will try that .. just signed up. They actually asked how I got to them .. and they seem to know you;)
